### ISSUE TITLE
line 115

### ISSUE THREAD

**Issue by crappy44** [Cr4sh/SmmBackdoor#1]
Line 115 throws errors. Typo?

```
cs.ints.send_SW_SMI(command, data, 0, 0, arg, 0, 0, 0)
```

  File "C:\SMMBD\SmmBackdoor.py", line 115, in send_sw_smi
    cs.ints.send_SW_SMI(command, data, 0, 0, arg, 0, 0, 0)
TypeError: send_SW_SMI() takes exactly 10 arguments (9 given)

**Comment by MaoJunhong** [comment]
How to fix this issue?

**Comment by Cr4sh** [comment]
Use older chipsec version or rewrite the code in order to support changed send_SW_SMI() function.
